import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const products=[
 {icon:'☕',title:'Canecas personalizadas',desc:'Sua marca em presentes e objetos para o dia a dia.'},
 {icon:'📔',title:'Planners profissionais',desc:'Papelaria personalizada para organizar sua rotina.'},
 {icon:'🎁',title:'Kits para equipes',desc:'Presentes corporativos e conjuntos sob encomenda.'}
];
const mugCatalog=[{"name":"Amor","image":"/catalogo/modelo-1.svg","desc":"Para quem você ama","category":"Pessoal"},{"name":"Amizade","image":"/catalogo/modelo-2.svg","desc":"Momentos especiais","category":"Pessoal"},{"name":"Pets","image":"/catalogo/modelo-3.svg","desc":"Seu melhor amigo","category":"Pessoal"},{"name":"Família","image":"/catalogo/modelo-4.svg","desc":"Lembranças únicas","category":"Pessoal"},{"name":"Games","image":"/catalogo/modelo-5.svg","desc":"Seu universo","category":"Pessoal"},{"name":"Motivação","image":"/catalogo/modelo-6.svg","desc":"Inspire todos os dias","category":"Pessoal"},{"name":"Viagem","image":"/catalogo/modelo-7.svg","desc":"Colecione memórias","category":"Pessoal"},{"name":"Formatura","image":"/catalogo/modelo-8.svg","desc":"Uma conquista única","category":"Pessoal"},{"name":"Aniversário","image":"/catalogo/modelo-9.svg","desc":"Celebre com carinho","category":"Pessoal"},{"name":"Nome e inicial","image":"/catalogo/modelo-10.svg","desc":"Um presente só seu","category":"Pessoal"},{"name":"Empresas","image":"/catalogo/modelo-11.svg","desc":"Sua marca em destaque","category":"Corporativo"},{"name":"Profissões","image":"/catalogo/modelo-12.svg","desc":"Presente profissional","category":"Corporativo"}];
const professionNames=['Psicanálise','Psicologia','Terapeutas','Medicina','Enfermagem','Educação','Direito','Engenharia','Empreendedores','Outras profissões'];
const translations={pt:{catalog:'Catálogo de canecas',custom:'Personalizar',quote:'Pedir orçamento',send:'Continuar no WhatsApp',name:'Nome ou frase',profession:'Profissão',language:'Idioma da impressão',color:'Cor do texto',preview:'Prévia ilustrativa',image:'Imagem de referência',notice:'A prévia é ilustrativa. Envie a imagem original no WhatsApp para confirmar a produção.'},en:{catalog:'Mug catalog',custom:'Customize',quote:'Request a quote',send:'Continue on WhatsApp',name:'Name or phrase',profession:'Profession',language:'Print language',color:'Text color',preview:'Illustrative preview',image:'Reference image',notice:'Preview for illustration only. Send your original image on WhatsApp to confirm production.'},fr:{catalog:'Catalogue de mugs',custom:'Personnaliser',quote:'Demander un devis',send:'Continuer sur WhatsApp',name:'Nom ou phrase',profession:'Profession',language:"Langue d’impression",color:'Couleur du texte',preview:'Aperçu illustratif',image:'Image de référence',notice:"Aperçu illustratif. Envoyez votre image originale sur WhatsApp pour confirmer la production."},es:{catalog:'Catálogo de tazas',custom:'Personalizar',quote:'Solicitar presupuesto',send:'Continuar por WhatsApp',name:'Nombre o frase',profession:'Profesión',language:'Idioma de impresión',color:'Color del texto',preview:'Vista previa ilustrativa',image:'Imagen de referencia',notice:'Vista previa ilustrativa. Envía tu imagen original por WhatsApp para confirmar la producción.'}};
const indicativePrices={Brasil:'R$ 49,90',Portugal:'€ 17,90'};
const whatsapp=(import.meta.env.VITE_ATELIER_WHATSAPP||'').replace(/\D/g,'');
function Landing(){
 const [country,setCountry]=useState('Portugal');
 const [product,setProduct]=useState('Kits para equipes');
 const [quantity,setQuantity]=useState('');
 const [details,setDetails]=useState('');
 const [destination,setDestination]=useState('');
 const [deadline,setDeadline]=useState('');
 const [reply,setReply]=useState('');
 const [feedback,setFeedback]=useState('');
 const [filter,setFilter]=useState('Todos');
 const [selected,setSelected]=useState(null);
 const [locale,setLocale]=useState('pt');
 const [customName,setCustomName]=useState('');
 const [customProfession,setCustomProfession]=useState('');
 const [customColor,setCustomColor]=useState('#a45266');
 const [printLanguage,setPrintLanguage]=useState('Português');
 const [referenceFile,setReferenceFile]=useState(null);
 const [consent,setConsent]=useState(false);
 const t=translations[locale];
 const selectModel=(x)=>{setSelected(x);setCustomName('');setCustomProfession(x.name==='Profissões'?'Psicanálise':'');setReferenceFile(null)};
 const applyCustomization=()=>{setProduct('Canecas personalizadas');setDetails('Modelo: '+selected.name+'; Texto: '+(customName||'a definir')+'; Profissão: '+(customProfession||'não aplicável')+'; Cor do texto: '+customColor+'; Idioma: '+printLanguage+(referenceFile?'; Imagem de referência: '+referenceFile.name+' (cliente enviará pelo WhatsApp)':''));setSelected(null);document.getElementById('orcamento')?.scrollIntoView({behavior:'smooth'})};
 const request=async(e)=>{
  e.preventDefault();
  if(!consent){setFeedback('Confirme que concorda em compartilhar os dados do pedido pelo WhatsApp.');return;}
  const message='ATELIÊ CLUB — Pedido de orçamento\nPaís: '+country+'\nProduto: '+product+'\nQuantidade: '+(quantity||'A definir')+'\nDestino (cidade/código postal): '+destination+'\nPrazo desejado: '+(deadline||'A combinar')+'\nContato: '+reply+'\nDetalhes: '+(details||'A definir')+'\nReferência indicativa (caneca, sem frete): '+(product==='Canecas personalizadas'?indicativePrices[country]:'Sob orçamento')+'\nPrazo estimado: 7 a 15 dias úteis após pagamento e aprovação da arte, sujeito a confirmação.'+'\nValor final a confirmar antes do pagamento.'+(referenceFile?'\nTenho uma imagem de referência para enviar no WhatsApp: '+referenceFile.name:'');
  if(!whatsapp){setFeedback('WhatsApp comercial ainda não configurado. Nenhum pedido foi enviado.');return;}
  const url='https://wa.me/'+whatsapp+'?text='+encodeURIComponent(message);
  const popup=window.open(url,'_blank','noopener,noreferrer');
  if(!popup){window.location.href=url;return;}
  setFeedback('Confira a mensagem no WhatsApp e toque em enviar. Caso tenha selecionado uma imagem, anexe-a manualmente na conversa.');
 };
 return <>
 <header className="shopHeader"><a href="#inicio" className="shopBrand"><span className="brandMark">♡</span><span>ATELIÊ CLUB<small>Personalizados que contam histórias</small></span></a><nav className="shopNav"><a href="#inicio">Início</a><a href="#catalogo">Canecas</a><a href="#orcamento" onClick={()=>setProduct('Planners profissionais')}>Planners</a><a href="#orcamento" onClick={()=>setProduct('Kits para equipes')}>Kits</a><a href="#como-funciona">Como funciona</a><a href="#orcamento">Contato</a></nav><div className="headerActions"><label className="languageSwitch">🌐 <select aria-label="Idioma / Language" value={locale} onChange={e=>setLocale(e.target.value)}><option value="pt">PT</option><option value="en">EN</option><option value="fr">FR</option><option value="es">ES</option></select></label><a className="shopButton shopHeaderButton" href={whatsapp?'https://wa.me/'+whatsapp+'?text='+encodeURIComponent('Olá! Gostaria de ver o catálogo do ATELIÊ CLUB.'):'#orcamento'}>☏ WhatsApp</a></div></header>
 <main id="inicio">
 <section className="shopHero"><div className="shopHeroCopy"><h1>Canecas<br/>Personalizadas<br/><em>para Todas as<br/>Ocasiões</em></h1><p>Transforme momentos simples em lembranças especiais com canecas personalizadas. Temos diversos temas e estilos, incluindo canecas para psicanalistas, psicólogos, terapeutas e profissionais de todas as áreas, em qualquer país. Imagens ilustrativas.</p><a className="shopButton" href="#catalogo">☏ {t.catalog}　›</a><div className="heroPerks"><span>♧ Produção<br/>sob encomenda</span><span>♙ Ideal para<br/>presentes</span><span>♡ Personalização<br/>do seu jeito</span><span>♥ Diversos temas<br/>e modelos</span></div></div><div className="heroMugs"><div className="heroMugsGrid">{mugCatalog.slice(0,4).map(x=><img src={x.image} alt={'Caneca ilustrativa: '+x.name}/>)}</div></div></section>
 <section className="themeStrip">{[{name:'Amor',icon:'♥'},{name:'Amizade',icon:'✿'},{name:'Pets',icon:'🐾'},{name:'Família',icon:'♡'},{name:'Games',icon:'🎮'},{name:'Motivação',icon:'✦'},{name:'Viagem',icon:'✈'},{name:'Formatura',icon:'🎓'},{name:'Aniversário',icon:'♔'},{name:'Nome e inicial',icon:'A'},{name:'Psicanálise',icon:'✧'},{name:'Psicologia',icon:'Ψ'},{name:'Terapeutas',icon:'♡'},{name:'Profissionais internacionais',icon:'🌐'},{name:'Medicina',icon:'⚕'},{name:'Enfermagem',icon:'✚'},{name:'Educação',icon:'✎'},{name:'Direito',icon:'⚖'},{name:'Engenharia',icon:'⌘'},{name:'Empreendedores',icon:'◆'},{name:'Outras profissões',icon:'✦'}].map((x,i)=><a href="#orcamento" onClick={()=>{setProduct('Canecas personalizadas');setDetails('Tema: '+x.name)}} key={x.name}><span className="themeIcon">{x.icon}</span><b>{x.name}</b></a>)}</section>
 <section className="shopGallery" id="catalogo"><h2>Alguns dos nossos modelos</h2><p>O mesmo catálogo de 12 temas apresentado no PDF do WhatsApp, agora com visual volumétrico e navegação interativa.</p><div className="catalogFilters" role="group" aria-label="Filtrar modelos">{['Todos','Pessoal','Corporativo','Profissões'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="mugGallery">{mugCatalog.filter(x=>filter==='Todos'||x.category===filter||(filter==='Profissões'&&x.name==='Profissões')).map(x=><button className="mugTile" key={x.name} onClick={()=>selectModel(x)} aria-label={'Ver detalhes de '+x.name}><img loading="lazy" src={x.image} alt={'Ilustração volumétrica de caneca personalizada: '+x.name}/><span className="mugTileText"><b>{x.name}</b><small>{x.desc}</small></span><span className="mugTileAction">{t.custom} ↗</span></button>)}</div><a className="shopButton galleryButton" href={whatsapp?'https://wa.me/'+whatsapp+'?text='+encodeURIComponent('Olá! Vi o catálogo ATELIÊ CLUB e gostaria de consultar os modelos e fazer um orçamento.'):'#orcamento'}>▣ Consultar Catálogo no WhatsApp　›</a><p className="imageDisclaimer">As imagens são meramente ilustrativas. O produto final pode apresentar diferenças de cores, impressão e acabamento. Modelos, disponibilidade, valores e prazos sujeitos à confirmação do fornecedor.</p></section>
 {selected&&<div className="catalogModalBackdrop" onClick={()=>setSelected(null)}><section className="catalogModal" role="dialog" aria-modal="true" aria-label={'Modelo '+selected.name} onClick={e=>e.stopPropagation()}><button className="catalogClose" onClick={()=>setSelected(null)} aria-label="Fechar">×</button><div className="catalogModalArt"><div className="previewLabel">{t.preview}</div><div className="previewMug"><img src={selected.image} alt={'Modelo '+selected.name}/>{(customName||customProfession)&&<div className="previewPrint" style={{color:customColor}}><strong>{customName.slice(0,24)}</strong><small>{customProfession.slice(0,25)}</small></div>}</div><small>{t.notice}</small></div><div className="catalogModalInfo"><span className="eyebrow">ATELIÊ CLUB · {t.custom}</span><h2>{selected.name}</h2><p>{selected.desc}</p><label>{t.name}<input maxLength="40" value={customName} onChange={e=>setCustomName(e.target.value)} placeholder="Ex.: Maria · Com carinho"/></label><label>{t.profession}<select value={customProfession} onChange={e=>setCustomProfession(e.target.value)}><option value="">—</option>{professionNames.map(x=><option key={x}>{x}</option>)}</select></label><label>{t.language}<select value={printLanguage} onChange={e=>setPrintLanguage(e.target.value)}>{['Português','English','Français','Español','Outro / Other'].map(x=><option key={x}>{x}</option>)}</select></label><label>{t.color}<input type="color" value={customColor} onChange={e=>setCustomColor(e.target.value)}/></label><label>{t.image}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setReferenceFile(e.target.files?.[0]||null)}/></label><p className="catalogPrice">{country}: <strong>{indicativePrices[country]}</strong></p><small>{t.notice} · Frete à parte.</small><button className="shopButton" onClick={applyCustomization}>{t.quote} →</button></div></section></div>}
 <section className="shopWhy"><h2>Por que escolher nossas canecas?</h2><div className="whyGrid"><div><strong>◇</strong><span><b>Personalização</b><small>Com fotos, nomes, frases e muito mais</small></span></div><div><strong>♔</strong><span><b>Ideais para presentes</b><small>Para várias ocasiões especiais</small></span></div><div><strong>♡</strong><span><b>Várias opções</b><small>Diversos temas e modelos</small></span></div><div><strong>♧</strong><span><b>Entrega sob consulta</b><small>Frete e prazo confirmados antes do pagamento</small></span></div></div><div className="shopPrice"><h2>Canecas Personalizadas a partir de <span>{indicativePrices[country]}</span></h2><div className="regionalPrices"><div><b>🇵🇹 Portugal — incluindo Porto</b><strong>€17,90</strong></div><div><b>🇧🇷 Brasil</b><strong>R$ 49,90</strong></div></div><p>Preços indicativos por unidade. Prazo estimado de produção e entrega: 7 a 15 dias úteis após confirmação do pagamento e da arte, sujeito à disponibilidade e ao destino. Frete calculado separadamente conforme a cidade e o código postal. Valor final e prazo confirmados pelo WhatsApp antes do pagamento.</p><div className="countryButtons"><button className={country==='Portugal'?'active':''} onClick={()=>setCountry('Portugal')}>Portugal</button><button className={country==='Brasil'?'active':''} onClick={()=>setCountry('Brasil')}>Brasil</button></div></div></section>
 <section className="shopHow" id="como-funciona"><h2>Como funciona</h2><p className="deliveryNotice">📦 Prazo estimado de produção e entrega: <strong>7 a 15 dias úteis</strong> após a confirmação do pagamento e da personalização. Sujeito à disponibilidade do fornecedor e ao destino; prazo final confirmado antes do pagamento.</p><div><span>1. Escolha seu modelo</span><span>2. Peça um orçamento</span><span>3. Confirme e pague pelo link seguro</span><span>4. Produção após pagamento</span></div></section>
 <section className="section lpFormSection" id="orcamento"><div><div className="eyebrow">PERSONALIZE DO SEU JEITO</div><h2>Peça seu orçamento</h2><p>Conte o que imagina e receba uma proposta. Para canecas, o valor de referência em {country} é {indicativePrices[country]}, com frete à parte. Planners e kits sob orçamento. Prazo estimado: 7 a 15 dias úteis, sujeito à confirmação conforme produto e destino.</p><p className="lpPrivacy">Use apenas dados necessários ao orçamento. As informações preenchidas serão incluídas na mensagem de WhatsApp, que você poderá revisar antes de enviar. A imagem selecionada não é enviada automaticamente.</p></div><form onSubmit={request}><label>País<select value={country} onChange={e=>setCountry(e.target.value)}><option>Portugal</option><option>Brasil</option></select></label><label>Produto<select value={product} onChange={e=>setProduct(e.target.value)}>{products.map(p=><option key={p.title}>{p.title}</option>)}</select></label><label>Quantidade<input required min="1" type="number" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="Ex.: 10"/></label><label>Cidade e código postal<input required value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Para calcular o frete"/></label><label>Prazo desejado<input value={deadline} onChange={e=>setDeadline(e.target.value)} placeholder="Data desejada"/></label><label>E-mail ou contato<input required value={reply} onChange={e=>setReply(e.target.value)} placeholder="Seu contato"/></label><label>Como deseja personalizar?<textarea value={details} onChange={e=>setDetails(e.target.value)} rows="3" placeholder="Tema, foto, nome, cores..."/></label><label className="orderConsent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Concordo em compartilhar os dados deste orçamento por WhatsApp e entendo que a mensagem só será enviada após minha confirmação no aplicativo.</label><div className="orderSummary" aria-live="polite"><strong>Resumo do pedido</strong><span>{product} · {country}</span><span>{quantity?quantity+" unidade(s)":"Quantidade a definir"} · {destination||"Destino a informar"}</span><span>{product==="Canecas personalizadas"?indicativePrices[country]+" por unidade (indicativo)":"Sob orçamento"} · Frete à parte</span><span>Estimativa: 7 a 15 dias úteis, sujeita à confirmação</span>{details&&<small>{details}</small>}</div><button className="shopButton" type="submit">{whatsapp?t.send+' →':'WhatsApp em configuração'}</button>{feedback&&<p className="warning" role="status">{feedback}</p>}</form></section>
 <section className="shopFaq" id="duvidas"><h2>Dúvidas frequentes</h2><details><summary>Os produtos são exatamente iguais às imagens?</summary><p>Não. As imagens são ilustrativas; cores, impressão e acabamento dependem do produto e da arte aprovada.</p></details><details><summary>Quando começa o prazo de 7 a 15 dias úteis?</summary><p>É uma estimativa de produção e entrega após confirmação do pagamento e aprovação da personalização. O prazo real depende do fornecedor e do destino e será confirmado antes de pagar.</p></details><details><summary>Como funciona o pagamento?</summary><p>Após confirmar o orçamento e a arte pelo WhatsApp, você recebe um link de pagamento. Não há cobrança automática ao preencher o formulário.</p></details><details><summary>Posso alterar ou cancelar meu pedido?</summary><p>Solicite pelo WhatsApp antes de aprovar a arte e pagar. Após o início da produção, a possibilidade de alterações ou cancelamento depende da fase do pedido e das regras aplicáveis, que serão informadas antes do pagamento.</p></details><details><summary>Como envio uma fotografia ou logotipo?</summary><p>Selecione uma imagem de referência no configurador e, ao abrir o WhatsApp, anexe manualmente o arquivo original. O site não envia nem armazena automaticamente esse arquivo.</p></details><details><summary>Entregam em Portugal e no Brasil?</summary><p>Os preços indicativos são €17,90 em Portugal, incluindo Porto, e R$49,90 no Brasil, por caneca. Confirme a disponibilidade e o frete para seu endereço antes do pagamento.</p></details></section>
 </main><footer><div><strong>ATELIÊ CLUB</strong><p>Personalizados que contam histórias.</p></div><div><p>Produção sob encomenda. Sem assinaturas.</p><p>Pagamento por link após confirmação do orçamento.</p></div></footer>
 </>;
}
createRoot(document.getElementById('root')).render(<Landing/>);
