import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const products=[
 {icon:'☕',title:'Canecas personalizadas',desc:'Sua marca em presentes e objetos para o dia a dia.'},
 {icon:'📔',title:'Planners profissionais',desc:'Papelaria personalizada para organizar sua rotina.'},
 {icon:'🎁',title:'Kits para equipes',desc:'Presentes corporativos e conjuntos sob encomenda.'}
];
const mugCatalog=[{"name":"Amor","image":"/catalogo/caneca-1.svg","desc":"Para alguém especial"},{"name":"Família","image":"/catalogo/caneca-2.svg","desc":"Memórias em família"},{"name":"Pets","image":"/catalogo/caneca-3.svg","desc":"Seu melhor amigo"},{"name":"Profissões","image":"/catalogo/caneca-4.svg","desc":"Sua marca aqui"},{"name":"Viagem","image":"/catalogo/caneca-5.svg","desc":"Colecione momentos"},{"name":"Aniversário","image":"/catalogo/caneca-6.svg","desc":"Celebre a vida"}];
const indicativePrices={Brasil:'R$ 49,90',Portugal:'€ 17,90'};
const whatsapp=(import.meta.env.VITE_ATELIER_WHATSAPP||'').replace(/\D/g,'');
function Landing(){
 const [country,setCountry]=useState('Portugal');
 const [product,setProduct]=useState('Kits para equipes');
 const [quantity,setQuantity]=useState('');
 const [details,setDetails]=useState('');
 const [destination,setDestination]=useState('');
 const [deadline,setDeadline]=useState('');
 const [reply,setReply]=useState('');
 const [feedback,setFeedback]=useState('');
 const request=async(e)=>{
  e.preventDefault();
  const message='ATELIÊ CLUB — Pedido de orçamento\nPaís: '+country+'\nProduto: '+product+'\nQuantidade: '+(quantity||'A definir')+'\nDestino (cidade/código postal): '+destination+'\nPrazo desejado: '+(deadline||'A combinar')+'\nContato: '+reply+'\nDetalhes: '+(details||'A definir')+'\nReferência indicativa (caneca, sem frete): '+(product==='Canecas personalizadas'?indicativePrices[country]:'Sob orçamento')+'\nValor final a confirmar antes do pagamento.';
  if(!whatsapp){setFeedback('WhatsApp comercial ainda não configurado. Nenhum pedido foi enviado.');return;}
  window.open('https://wa.me/'+whatsapp+'?text='+encodeURIComponent(message),'_blank','noopener,noreferrer');
  setFeedback('O WhatsApp foi aberto. Confirme o envio da mensagem para concluir sua solicitação.');
 };
 return <>
 <header className="shopHeader"><a href="#inicio" className="shopBrand"><span className="brandMark">♡</span><span>ATELIÊ CLUB<small>Personalizados que contam histórias</small></span></a><nav className="shopNav"><a href="#inicio">Início</a><a href="#catalogo">Canecas</a><a href="#orcamento" onClick={()=>setProduct('Planners profissionais')}>Planners</a><a href="#orcamento" onClick={()=>setProduct('Kits para equipes')}>Kits</a><a href="#como-funciona">Como funciona</a><a href="#orcamento">Contato</a></nav><a className="shopButton shopHeaderButton" href={whatsapp?'https://wa.me/'+whatsapp+'?text='+encodeURIComponent('Olá! Gostaria de ver o catálogo do ATELIÊ CLUB.'):'#orcamento'}>☏ Falar no WhatsApp</a></header>
 <main id="inicio">
 <section className="shopHero"><div className="shopHeroCopy"><h1>Canecas<br/>Personalizadas<br/><em>para Todas as<br/>Ocasiões</em></h1><p>Transforme momentos simples em lembranças especiais com canecas personalizadas. Temos diversos modelos, temas e estilos para você, presentear ou usar no dia a dia.</p><a className="shopButton" href="#catalogo">☏ Ver Catálogo de Canecas　›</a><div className="heroPerks"><span>♧ Produção<br/>sob encomenda</span><span>♙ Ideal para<br/>presentes</span><span>♡ Personalização<br/>do seu jeito</span><span>♥ Diversos temas<br/>e modelos</span></div></div><div className="heroMugs"><div className="heroMugsGrid">{mugCatalog.slice(0,4).map(x=><img src={x.image} alt={'Caneca ilustrativa: '+x.name}/>)}</div></div></section>
 <section className="themeStrip">{[{name:'Amor',icon:'♥'},{name:'Amizade',icon:'✿'},{name:'Pets',icon:'🐾'},{name:'Família',icon:'♡'},{name:'Games',icon:'🎮'},{name:'Motivação',icon:'✦'},{name:'Viagem',icon:'✈'},{name:'Formatura',icon:'🎓'},{name:'Aniversário',icon:'♔'},{name:'Nome e inicial',icon:'A'}].map((x,i)=><a href="#orcamento" onClick={()=>{setProduct('Canecas personalizadas');setDetails('Tema: '+x.name)}} key={x.name}><span className="themeIcon">{x.icon}</span><b>{x.name}</b></a>)}</section>
 <section className="shopGallery" id="catalogo"><h2>Alguns dos nossos modelos</h2><p>Temos várias opções de canecas personalizadas. Confira alguns exemplos ilustrativos:</p><div className="mugGallery">{[...mugCatalog,...mugCatalog].map((x,i)=><a href="#orcamento" key={i} onClick={()=>{setProduct('Canecas personalizadas');setDetails('Modelo ilustrativo: '+x.name)}}><img loading="lazy" src={x.image} alt={'Modelo ilustrativo de caneca: '+x.name}/></a>)}</div><a className="shopButton galleryButton" href={whatsapp?'https://wa.me/'+whatsapp+'?text='+encodeURIComponent('Olá! Gostaria de receber o catálogo completo de canecas e consultar os modelos disponíveis.'):'#orcamento'}>▣ Ver Catálogo Completo no WhatsApp　›</a><p className="imageDisclaimer">Imagens ilustrativas. Modelos e personalização sujeitos à confirmação do fornecedor.</p></section>
 <section className="shopWhy"><h2>Por que escolher nossas canecas?</h2><div className="whyGrid"><div><strong>◇</strong><span><b>Personalização</b><small>Com fotos, nomes, frases e muito mais</small></span></div><div><strong>♔</strong><span><b>Ideais para presentes</b><small>Para várias ocasiões especiais</small></span></div><div><strong>♡</strong><span><b>Várias opções</b><small>Diversos temas e modelos</small></span></div><div><strong>♧</strong><span><b>Entrega sob consulta</b><small>Frete e prazo confirmados antes do pagamento</small></span></div></div><div className="shopPrice"><h2>Canecas Personalizadas a partir de <span>{indicativePrices[country]}</span></h2><p>Referência para {country}. Frete calculado separadamente. Valor final confirmado no WhatsApp.</p><div className="countryButtons"><button className={country==='Portugal'?'active':''} onClick={()=>setCountry('Portugal')}>Portugal</button><button className={country==='Brasil'?'active':''} onClick={()=>setCountry('Brasil')}>Brasil</button></div></div></section>
 <section className="shopHow" id="como-funciona"><h2>Como funciona</h2><div><span>1. Escolha seu modelo</span><span>2. Peça um orçamento</span><span>3. Confirme e pague pelo link seguro</span><span>4. Produção após pagamento</span></div></section>
 <section className="section lpFormSection" id="orcamento"><div><div className="eyebrow">PERSONALIZE DO SEU JEITO</div><h2>Peça seu orçamento</h2><p>Conte o que imagina e receba uma proposta. Para canecas, o valor de referência em {country} é {indicativePrices[country]}, com frete à parte. Planners e kits sob orçamento.</p><p className="lpPrivacy">Não envie informações sensíveis.</p></div><form onSubmit={request}><label>País<select value={country} onChange={e=>setCountry(e.target.value)}><option>Portugal</option><option>Brasil</option></select></label><label>Produto<select value={product} onChange={e=>setProduct(e.target.value)}>{products.map(p=><option key={p.title}>{p.title}</option>)}</select></label><label>Quantidade<input required min="1" type="number" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="Ex.: 10"/></label><label>Cidade e código postal<input required value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Para calcular o frete"/></label><label>Prazo desejado<input value={deadline} onChange={e=>setDeadline(e.target.value)} placeholder="Data desejada"/></label><label>E-mail ou contato<input required value={reply} onChange={e=>setReply(e.target.value)} placeholder="Seu contato"/></label><label>Como deseja personalizar?<textarea value={details} onChange={e=>setDetails(e.target.value)} rows="3" placeholder="Tema, foto, nome, cores..."/></label><button className="shopButton" type="submit">{whatsapp?'Continuar pedido no WhatsApp →':'WhatsApp em configuração'}</button>{feedback&&<p className="warning" role="status">{feedback}</p>}</form></section>
 </main><footer><div><strong>ATELIÊ CLUB</strong><p>Personalizados que contam histórias.</p></div><div><p>Produção sob encomenda. Sem assinaturas.</p><p>Pagamento por link após confirmação do orçamento.</p></div></footer>
 </>;
}
createRoot(document.getElementById('root')).render(<Landing/>);
