import React,{useEffect,useState} from 'react';
import{createClient}from'@supabase/supabase-js';
const url=import.meta.env.VITE_SUPABASE_URL;
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const db=url&&key?createClient(url,key):null;
export default function Portal(){const[session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[orders,setOrders]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
useEffect(()=>{if(!db)return;db.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=db.auth.onAuthStateChange((_event,next)=>setSession(next));return()=>subscription.unsubscribe()},[]);
const role=session?.user?.app_metadata?.atelier_role;const country=session?.user?.app_metadata?.atelier_country;
useEffect(()=>{if(!db||!session||!['admin','operator'].includes(role))return;setLoading(true);db.from('atelier_orders').select('id,country,status,created_at,items,total_minor,currency,customer_name,shipping_address,carrier,tracking_code').order('created_at',{ascending:false}).limit(100).then(({data,error})=>{setLoading(false);if(error)setError(error.message);else setOrders(data||[])})},[session,role]);
async function login(e){e.preventDefault();setError('');const{error}=await db.auth.signInWithPassword({email,password});if(error)setError('Não foi possível entrar. Confira seus dados.')}
return <main className="section narrow"><div className="eyebrow">ATELIÊ CLUB · ÁREA RESTRITA</div><h1 className="pageTitle">Painel de encomendas</h1>{!db?<p className="warning">Painel em configuração. É necessário um banco de dados exclusivo para o ATELIÊ CLUB.</p>:!session?<form onSubmit={login}><label>E-mail profissional<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" type="submit">Entrar</button>{error&&<p role="alert">{error}</p>}</form>:!['admin','operator'].includes(role)||role==='operator'&&!['BR','PT'].includes(country)?<><p className="warning">Seu acesso ao ATELIÊ CLUB ainda não foi autorizado.</p><button onClick={()=>db.auth.signOut()}>Sair</button></>:<><p>{role==='admin'?'Administrador — Brasil e Portugal':country==='BR'?'Operação Brasil':'Operação Portugal'}</p><button onClick={()=>db.auth.signOut()}>Sair</button>{error&&<p role="alert">{error}</p>}{loading?<p>Carregando pedidos…</p>:orders.length===0?<p>Não há pedidos disponíveis.</p>:<div className="cartList">{orders.map(o=><article key={o.id} className="cartItem"><div><b>Pedido {o.id.slice(0,8)}</b><p>{o.country} · {o.status} · {new Date(o.created_at).toLocaleDateString()}</p><p>{o.customer_name||'Cliente'} · {o.items?.length||0} item(ns)</p><p>{o.carrier?o.carrier+' · '+(o.tracking_code||'sem rastreio'):'Aguardando atualização'}</p></div><strong>{new Intl.NumberFormat(o.country==='BR'?'pt-BR':'pt-PT',{style:'currency',currency:o.currency}).format(o.total_minor/100)}</strong></article>)}</div>}<p className="warning">Consulta inicial de pedidos. Assumir pedidos e registrar envios serão habilitados após validação do backend e das permissões.</p></>}</main>}
